CREATE TABLE Users (
  UserID INTEGER PRIMARY KEY,
  Name TEXT NOT NULL,
  Email TEXT UNIQUE NOT NULL
);

CREATE TABLE Classes (
  ClassID INTEGER PRIMARY KEY,
  ClassName TEXT NOT NULL,
  Schedule TEXT NOT NULL,
  Capacity INTEGER NOT NULL
);

CREATE TABLE Bookings (
  BookingID INTEGER PRIMARY KEY,
  UserID INTEGER,
  ClassID INTEGER,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (ClassID) REFERENCES Classes(ClassID)
);

CREATE TABLE Attendance (
  AttendanceID INTEGER PRIMARY KEY,
  UserID INTEGER,
  ClassID INTEGER,
  AttendanceDate TEXT NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (ClassID) REFERENCES Classes(ClassID)
);
