name: Continuous Integration
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r ./23/requirements.txt
      working-directory: ./23
    - name: Run tests
      run: |
        pytest
      working-directory: ./23
